# Generated by Django 3.1 on 2020-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
        migrations.AddField(
            model_name='entry',
            name='titles',
            field=models.CharField(default='妮妮vdsi及', max_length=200),
            preserve_default=False,
        ),
    ]
